apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: myregistry.azurecr.io/ac-image:latest
        ports:
        - containerPort: 8080
        env:
        - name: ENV_VAR_NAME
          value: ENV_VAR_VALUE
